Enriched scrolling experience
dreamirl/de-plugin-gui pull request #7
Opened 2022-03-01 15:29 UTC by Sealed001

Enabling horizontal wheel movement and adding support for scrolling with the opposite scroll wheel direction

2022-03-01 16:28 UTC, Zeksa requested changes
+ ne pas oublier il faut update le numéro de version du package.json

2022-03-01 16:28 UTC, Zeksa commented on ScrollContainer.js
> +        );
de mon côté ça ne marche pas. Pourquoi ne pas simplement faire

```
this.onscroll = function(event) {
      if (!this.locked && this.pointerInside) {
        const scroll = this.mouseScrollSpeed * -event.deltaY
        this.scroll(scroll, scroll);
      }
};
```

2022-03-01 16:31 UTC, Sealed001 commented on ScrollContainer.js
> +        );
ta pull achievements

2022-03-01 16:33 UTC, Zeksa commented on ScrollContainer.js
> +        );
Ce n'est pas une bonne idée de demander un paramètre pour un résultat qu'on souhaite avoir par défaut

2022-03-02 08:47 UTC, Zeksa requested changes

2022-03-02 08:47 UTC, Zeksa commented on ScrollContainer.js
> +    this.scrollXVerticalScroll = scrollContainerParams.scrollXVerticalScroll;
pourquoi ajouter des paramètres pour un résultat qu'on veut tout le temps présent ? ça rajoute de la complexité

2022-03-02 08:47 UTC, Zeksa commented on ScrollContainer.js
> +    this.scrollXVerticalScroll = scrollContainerParams.scrollXVerticalScroll;
Dans quel cas ta PR est pertinente par rapport à juste changer deux lignes pour faire le code que j'ai mis en comm

2022-03-28 11:45 UTC, closed without merging